travis:
  secure:
    BINSTAR_TOKEN: I491QSF1s91ExZCpKknr38RhWM0f9ZpcwgDiJCHbDliwdTWDdJLYqkIwp65suRMPHD5oKtF1dgvjHnJpnpBWqSs5QdK0mpqPZ8o/KlYvRjRYr+Mt+NxSHyzL4NhPYAYYn86Lj0KFHeSF8tRICpIRJ2bMVi0wF3kgZAcqyHFORYVefFQhfKbSLbil3GvP/i5V1tkRraS2KnadAtkZYCuboOg9ZGhj9GMgjLfPLoop0GgJmyi4pCmTAv7VGVubpOoY1jWAEaH47drBj/ouZZQ3BS3/nm/qiWFRhgeMfBLk3mA/pHANwaI+aIzmmCl2yGIiA5DLR5su/qfBX7OvjnfYLSngh6BIi2re9kslM2t7CmMSe+Gf8K3hx7X8S1pvnI9ku+cx/nn4TfITuzNtOuuR1HK4H7/xroB5aU6B/b/qzquG6PMpyYh3DJNAPzFwe0mbhMBv8nzLrtRbZiGrLAXsxP/vZZ4T0XkKrRnOwYrWZzARVCsk3TyX4MqvMxRnD5FwSaleI3+MvE9DtO4VuuEb0VtH5P91or+lqrDnYGI3wa7MF0Z7WQGbSODGmuLLuyBsMQeC93PA+k3gvTfM2Y7wVSyBF5LSql873510NtMx8N3lHutnEtJ3UAgDsQcIws5mlg+0mr8lsX+vxQzSweNV3J/I3CfQE33ELyV73C4toGU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
