travis:
  secure:
    BINSTAR_TOKEN: Kc3KSRwVJm9huts7FFFM5b05SL0TR00NZktHJsrZWQj8GEAubNvFZF6rfxOK/0/ydqsdfbIfZwNEsFxN40WQ9NmQEr4EoCb77icIxTrkfpDT9z1d8fkqxCyKf+PRBrSCsVmk15HoHEHfL8S4OXVUF+Brbu3NYmH2HY0QBEGaCXsaMvZxcf2Rjz5EfA0yveqwqfDW0n7QKOyfMx0EhdqUVArEiJA7tsUmshEqUFeRuAkiBsXaCzkVbdJJGSiG6XLjqaEWYMg926YB3F617WOh0SXEQhcosn49K6w0RtNnBnk9+4oM/+k6+ikAfhd4ZCdTe7m8UVgZ9NJlOROXB35ZLFdNAlgHzOf2ZLIhoyGpP5nkCF41JIKsOH4ze+4upL5flFiB5WXWuMDYurLoCrLpGzEzGnFFNC/Br18NKkVMw8Klm7em8AFjElX8kHhe7JhkGZ0EuBKQjxvqr4Sv/5/OOoUqhjy0rM8jc12DdYkha5Y5QuzhybHMkJsqWdbKIZ9ogeWpT52VY/t9LYYcF+sWZqC1ATMYwn6JsIwife6CH/oE+TOdtc0gJl0SruKKPdlDfU/pVTKnBTg/yBgEt4A2oQy9659TftNIGQjFV65qZvmkw1Rmm+pSneubx7JOUbfCEJx7AJNJV50ziZHIk+fyD7If9NEOZkDK9rzR1KzIJA4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
